services:
  ishtech-springboot-multi-port:
    build:
      context: .
      dockerfile: Dockerfile
    image: muneer2ishtech/ishtech-springboot-multi-port${APP_VERSION:+:$APP_VERSION}
    container_name: ishtech_springboot_multi_port
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      SERVER_PORT: ${SERVER_PORT:-8080}
      FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_ADDITIONAL_PORTS: ${FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_ADDITIONAL_PORTS:-false}
      FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_BOOK_PORT: ${FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_BOOK_PORT:-8081}
      FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_USER_PORT: ${FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_USER_PORT:-8082}
    ports:
      - "${SERVER_PORT_LOCAL:-${SERVER_PORT:-8080}}:${SERVER_PORT:-8080}"
      - "${FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_BOOK_PORT:-8081}:${FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_BOOK_PORT:-8081}"
      - "${FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_USER_PORT:-8082}:${FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_USER_PORT:-8082}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT:-8080}/actuator/health"]
      start_period: 60s
