# ====== Stage 1: Build ======
FROM eclipse-temurin:25-jdk AS build

WORKDIR /app

COPY . .

ARG MAVEN_CLI_OPTS="-B -q -s .mvn/settings.xml"

RUN chmod +x ./mvnw

RUN ./mvnw $MAVEN_CLI_OPTS clean package -DskipTests=true

# ====== Stage 2: Runtime ======
FROM eclipse-temurin:25-jre

WORKDIR /app

COPY --from=build /app/target/ishtech-springboot-multi-port-*.jar ishtech-springboot-multi-port.jar

# For building image with custom ports and properties
ARG SERVER_PORT=8080
ARG FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_BOOK_PORT=8081
ARG FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_USER_PORT=8082
ARG FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_ADDITIONAL_PORTS=false

ENV SERVER_PORT=${SERVER_PORT}
ENV FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_BOOK_PORT=${FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_BOOK_PORT}
ENV FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_USER_PORT=${FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_USER_PORT}
ENV FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_ADDITIONAL_PORTS=${FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_ADDITIONAL_PORTS}

EXPOSE ${SERVER_PORT}
EXPOSE ${FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_BOOK_PORT}
EXPOSE ${FI_ISHTECH_PRACTICE_SPRINGBOOT_MULTIPORT_USER_PORT}

ENTRYPOINT ["java", "-jar", "ishtech-springboot-multi-port.jar"]
